### ISSUE TITLE
Disable only one direction

### ISSUE THREAD

**Issue by kata32** [aitsuki/SwipeMenuRecyclerView#15]
How can I disable only one direction swipe (left or right)?

**Comment by aitsuki** [comment]
No, there is no way to disable only one direction. But i will provide this feature in a few days.

**Comment by aitsuki** [comment]
I added a new field swipeFlags to control the available swipe directions. For example, If you want to disable the left swipe, set the swipeFlags value to SwipleLayout.RIGHT.
```kotlin
swipeLayout.swipeFlags = SwipeLayout.RIGHT
```

other use case:
- enable all directions:  `swipeLayout.swipeFlags = SwipeLayout.LEFT and SwipeLayout.RIGHT`
- disable all directions:  `swipeLayout.swipeFlags = 0`

I will release a new version 2.1.0. 
If you have other suggestions, please reopen this issue.
