### ISSUE TITLE
How to cancel the sliding function?

### ISSUE THREAD

**Issue by qq709238339** [AItsuki/SwipeMenuRecyclerView#2]
Hi :
     Thank you for your library,it's really helpful to me !
     I wanna how to cancel the SwipeItemLayout‘s sliding function？Can you add the api ?

**Comment by AItsuki** [comment]
是禁止滑动吗

**Comment by qq709238339** [comment]
是的，因为RecyclerView有些item不想要侧滑菜单功能。目前我是用的两个viewType来解决的

**Comment by AItsuki** [comment]
加上去了……就是一个setSwipeEnable方法，之前漏了。
还有一些开关滑动之类的回调监听我没写……

**Comment by qq709238339** [comment]
。。。3q
项目赶进度，没仔细去研究你写的代码，笑哭了。。。
