### ISSUE TITLE
RTL 支持

### ISSUE THREAD

**Issue by kakarrot** [aitsuki/SwipeMenuRecyclerView#22]
当布局切换成 `RTL` 以后，LEFT 和 RIGHT 会调换位置，所以在布局上已经没什么问题，但实际上此时 rightMenu 在左侧，leftMenu在右侧，故：openXXXMenu() 和 closeXXXMenu() 操作的是相反的 menu, 只需要添加一行判断，如果是 `RTL` 布局就判断 activeMenu 是否是相反的 menu 即可

```kotlin
private val isRtl by lazy {
        TextUtilsCompat.getLayoutDirectionFromLocale(Locale.getDefault()) == ViewCompat.LAYOUT_DIRECTION_RTL
}
```

```kotlin
fun openLeftMenu(animate: Boolean = true) {
        activeMenu = if(isRtl) rightMenu else leftMenu
        openActiveMenu(animate)
}
```
同理：
```kotlin
fun isLeftMenuOpened(): Boolean {
        val activeMenu = activeMenu ?: return false
        return activeMenu == (if(isRtl) rightMenu else leftMenu) && openState and FLAG_IS_OPENED == FLAG_IS_OPENED
}

fun isRightMenuOpened(): Boolean {
        val activeMenu = activeMenu ?: return false
        return activeMenu == (if(isRtl) leftMenu else rightMenu) && openState and FLAG_IS_OPENED == FLAG_IS_OPENED
 }

```

**Comment by aitsuki** [comment]
好的，我稍微试了一下发现改RTL后还会有其他小问题，例如parallax的顺序错了。我找时间一并修复后再发个新版本吧

**Comment by aitsuki** [comment]
我发现切换RTL布局后，所有类型的菜单都出现了问题，原因是Designer的onInit方法的回调时机有误。
目前已修复这个Bug https://github.com/aitsuki/SwipeMenuRecyclerView/commit/64535f15126f02b70b7b8aaded944874da535f1e#

另外，我暂时不会修改OpenLeftMenu和OpenRightMenu这几个方法，我不确定它们的行为是否真的是错的，毕竟阿拉伯人的左边和我们的左边是同一个概念，只是Android为了适配RTL把我们弄混乱了。

你可能需要的是OpenStartMenu和OpenEndMenu这几个方法。

**Comment by kakarrot** [comment]
> 
嗯，确实如此，`openLeftMenu()`  和 `openRightMenu()` 的方法可以不变，新增加 `openStartMenu` 和 `openEndMenu()` 更好
