### ISSUE TITLE
怎么混合使用?左边LongMenu, 右边Parallax

### ISSUE THREAD

**Issue by wangzhankai** [aitsuki/SwipeMenuRecyclerView#23]
怎么混合使用?左边LongMenu, 右边Parallax，左边LongMenu的时候，如果距离小，显示Classic，如果距离大的时候，是LongMenu。可以实现这种效果吗

**Comment by aitsuki** [comment]
首先，LongMenu并不是一种Designer，只是菜单铺满父布局而已。
另外，左右菜单共用一个Designer，而内置实现的各种Designer（Classic，Overlay，Parallax）都是左右菜单使用相同的样式。
所以，想实现你需求很简单，只需要参考内置的Designer自定义你的Desinger即可。
