### ISSUE TITLE
How to identify which menuView currently open ? e.g LeftMenu,Right etc

### ISSUE THREAD

**Issue by Yousaf128** [aitsuki/SwipeMenuRecyclerView#25]
When we swipe View how to identify which menu currently open .

**Comment by aitsuki** [comment]
https://github.com/aitsuki/SwipeMenuRecyclerView/blob/6cbe597f97b43781a1611919c69079704f17aa2f/library/src/main/java/com/aitsuki/swipe/SwipeLayout.kt#L130-L138

Can this help you?
