### ISSUE TITLE
不适配（某些手机无法开启菜单）

### ISSUE THREAD

**Issue by moruhui** [AItsuki/SwipeMenuRecyclerView#3]
红米note3手机左右滑动，还没点击删除操作自动又返回原样

**Comment by AItsuki** [comment]
嗯 我排查下试试，手头上机子都测过了没问题…… 有点难度

**Comment by AItsuki** [comment]
额 具体操作是怎样的……  滑动开了菜单，只要不是触摸事件不是发生在菜单上都是默认关闭菜单的

**Comment by AItsuki** [comment]
我测试过手头上所有的手机加模拟器都没有问题…… 可惜我没有note3……

**Comment by moruhui** [comment]
本身要用你这个来着，结果安装同事手机，向右滑动时，删除的TextView出来，没过500毫秒自动又原路返回，在这之间我没碰过屏幕

**Comment by AItsuki** [comment]
这就有点牛逼了，500毫秒后原路返回，我没做任何定时任务啊……
有空的时候能不能帮我debug一下为什么会自动返回去额。我这边手机都没事……

**Comment by AItsuki** [comment]
借了几部同事的手机， 在一部魅蓝上发现了这个问题，而魅族是没有问题…… 
我测试下，改好了再通知你吧

**Comment by AItsuki** [comment]
改好了，这是因为在某些机子上setVisibility会导致draghelper失效。具体原因不明，我已经用clickable代替setVisibility了。
