### ISSUE TITLE
当侧滑菜单展开时，点击菜单内的View会自动关闭菜单，希望是否自动关闭可以让用户自己控制

### ISSUE THREAD

**Issue by BestDreams** [aitsuki/SwipeMenuRecyclerView#32]
大佬好，有一个需求，当侧滑菜单展开时，点击菜单内的View会自动关闭菜单，希望能增加一个是否自动关闭可以让用户控制的开关，如果设置成不自动关闭，用户可以自行在点击事件里调用关闭菜单

**Comment by aitsuki** [comment]
我记得有个autoClose的属性吧
https://github.com/aitsuki/SwipeMenuRecyclerView#swipelayout-%E7%9A%84%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%9E%E6%80%A7

**Comment by BestDreams** [comment]
哦哦，看到了，我自己理解错了，刚试了下可以实现，不好意思
