### ISSUE TITLE
轮询数据对RecyclerView刷新时，openMenu错位

### ISSUE THREAD

**Issue by JMcico** [aitsuki/SwipeMenuRecyclerView#38]
我在使用SwipeRecyclerView的时候，用协程和retrofit从服务端数据库读取数据并更新UI，但在刷新过程中发现滑出来的Menu会在刷新UI的时候上移4~6位，即原来打开的是15的item的菜单，会突然变成11的item打开菜单。请问这是该如何进行调整才能避免在adapter中使用notifyDataSetChanged()时不会出现这个问题？

**Comment by aitsuki** [comment]
记录下item Id对应的状态就好了，比如列表的单选和多选是如何实现的。

**Comment by yuluowusheng** [comment]
跟单选和多选有一个区别：notifyDataSetChanged()时，原始打开位置的左滑菜单默认隐藏，我记录状态，onbindView时再打开，有一个闪现的过程，体验十分不好

**Comment by yuluowusheng** [comment]
而且onBindView时直接调用openmenu无效，必须等到onMesuer结束之后才行，我现在是这样做的
//binding.swipeLayout.openRightMenu(false) 此时menu为空，不会执行
            binding.swipeLayout.post { //必须等到绘制完成才行，这样就会闪现
                binding.swipeLayout.openRightMenu(false)
            }
