### ISSUE TITLE
RecyclerView父控件是SwipeRefreshLayout时，侧滑时会出现下拉刷新

### ISSUE THREAD

**Issue by 1196278096** [AItsuki/SwipeMenuRecyclerView#4]
RecyclerView父控件是SwipeRefreshLayout时，侧滑时会出现下拉刷新，请问一下这该怎么解决？

**Comment by AItsuki** [comment]
这个是SwipeRefreshLayout自身问题……
SwipeRefreshLayout和ViewPager一起使用也会出现这个问题……
可以看看我以前这篇文章解决 http://blog.csdn.net/u010386612/article/details/50548977
