### ISSUE TITLE
background 设置后拖拽异常

### ISSUE THREAD

**Issue by KunNiu** [aitsuki/SwipeMenuRecyclerView#5]
采用shape的方式自定义的background，如果设置给content，则menu的拖拽效果会失效，会变成突然出现的样子

**Comment by AItsuki** [comment]
我以前以为我已经解决了这个问题，没想到还存在。我有空就看看，但是手头上测试机只有一部，有些问题可能无法复现

**Comment by AItsuki** [comment]
@persist1234 我无法复现你们的问题，这和设备有关，能否在Activity上关闭硬件加速后再试试，期待反馈。
